Repository timescale/docs.timescale.com-content, pull requests merged in 2018-12, with the labels that each got.

#57 Add description of timescaledb_information.hypertable
  api.md
Labels: 1.1

#60 Update README
  README.md
Labels: 1.0

#61 Adds documentation for show_chunks function, updates drop_chunks
  api.md
Labels: 1.1

#63 Change function title size
  api.md
Labels: 0.12
