Repository timescale/docs.timescale.com-content, pull requests merged in 2018-10, with the labels that each got.

#46 Add documentation for the time_bucket origin parameter
  api.md
Labels: 1.0

#45 Update apt installation pages to be more streamline
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
Labels: 0.12, 1.0

#47 Reword phrase
  getting-started/configuring.md
Labels: 0.8

#48 Update README to describe PR labelling
  README.md
Labels: 0.8
