Repository timescale/docs.timescale.com-content, pull requests merged in 2019-07, with the labels that each got.

#168 Remove PostgreSQL version option from cloud
  page-index/page-index.js
Labels: 1.3

#179 Merging clustering with most recent master branch
  CODEOWNERS
  api.md
  getting-started/installation-timescale-cloud.md
  page-index/page-index.js
  using-timescaledb/continuous-aggregates.md
Labels: clustering

#187 Remove adaptive terminology
  introduction/architecture.md
Labels: 1.5

#186 Add CTAs to installation for clustering
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
  getting-started/installation-homebrew.md
  getting-started/installation-source-windows.md
  getting-started/installation-timescale-cloud.md
  getting-started/installation-ubuntu-ami.md
  getting-started/installation-windows-azure.md
  getting-started/installation-windows.md
  getting-started/installation-yum.md
Labels: clustering

#169 Initial architectural overview re clustering
  introduction/architecture.md
Labels: clustering

#185 Add in timescaledb_info.data_node
  api.md
Labels: clustering

#178 Add in clustering tutorial
  page-index/page-index.js
  tutorials.md
  tutorials/clustering.md
Labels: clustering

#183 Document `create_distributed_hypertable`
  api.md
Labels: clustering

#189 Make hypertable one word
  api.md
Labels: 1.0

#188 Deprecate adaptive chunking for future versions
  api.md
Labels: 1.5

#180 Add chapter about scaling out
  .gitignore
  getting-started/scaling-out.md
  page-index/page-index.js
Labels: clustering

#177 Reference documentation for `attach_data_node` and `detach_data_node`
  api.md
Labels: clustering

#171 Reference documentation for add_data_node and delete_data_node
  api.md
Labels: clustering

#192 Attach data node documentation
  api.md
Labels: clustering

#195 Fix ordering of detach_data_node command
  api.md
Labels: clustering

#197 Add in warnings and CTAs for clustering private beta
  getting-started/scaling-out.md
  introduction/architecture.md
  tutorials/clustering.md
Labels: clustering

#203 Add warning about CASCADE
  api.md
Labels: clustering

#204 Add CASCADE option to delete_data_node and warning
  getting-started/scaling-out.md
Labels: clustering

#200 Adjust documentation regarding metadata table
  using-timescaledb/telemetry.md
Labels: 1.4

#205 Remove quotes from 'true'
  api.md
Labels: clustering

#202 Continuous aggregate doc update
  api.md
  tutorials/continuous-aggs-tutorial.md
  using-timescaledb/continuous-aggregates.md
Labels: 1.4

#201 Add architecture fields to telemetry page
  using-timescaledb/telemetry.md
Labels: 1.4

#190 Clarify docker-compose method
  tutorials/prometheus-adapter.md
Labels: 0.8

#208 Update AMI IDs for 1.4.0
  getting-started/installation-ubuntu-ami.md
Labels: 1.4

#173 Update drop_chunks return behavior
  api.md
Labels: 1.5

#209 Fix example interpolate query.
  api.md
Labels: 1.2

#212 Typo in continuous-aggregates.md
  using-timescaledb/continuous-aggregates.md
Labels: 1.2

#211 Update used Telegraf version
  tutorials/telegraf-output-plugin.md
Labels: 1.0

#214 Fix CentOS 7 install sudo error
  getting-started/installation-yum.md
Labels: 0.8, bug
