Repository timescale/docs.timescale.com-content, pull requests merged in 2019-06, with the labels that each got.

#151 Add warning regarding telemetry in setup docs
  getting-started/setup.md
Labels: 0.12

#105 Remove space partitioning discussion from best practices
  api.md
  getting-started/creating-hypertables.md
Labels: 0.8

#154 Create alerting.md
  using-timescaledb/alerting.md
Labels: 1.2

#155 Add in alerting link in sidebar
  page-index/page-index.js
Labels: 1.2

#152 Add in docs regarding up-to-date cont aggs
  api.md
  tutorials/continuous-aggs-tutorial.md
  using-timescaledb/continuous-aggregates.md
Labels: 1.3

#157 Update Windows instructions and other small nits
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
  getting-started/installation-homebrew.md
  getting-started/installation-source-windows.md
  getting-started/installation-source.md
  getting-started/installation-windows.md
  getting-started/installation-yum.md
Labels: 1.3

#162 Add tooling link in sidebar
  page-index/page-index.js
Labels: 1.3, updated content

#161 Create tooling.md
  using-timescaledb/tooling.md
Labels: 1.3, new content

#158 Bring prometheus adapter tutorial up to date
  tutorials/prometheus-adapter.md
Labels: 1.3

#163 Change Intro title
  page-index/page-index.js
Labels: 0.8

#160 Update get_telemetry_report
  api.md
Labels: 1.4
