Repository timescale/docs.timescale.com-content, pull requests merged in 2019-01, with the labels that each got.

#71 Improve notation of link in the in the Hello NYC tutorial
  tutorials/tutorial-hello-nyc.md
Labels: 0.8, updated content

#72 Update a list of schemas for the latest version
  tutorials/tutorial-hello-nyc.md
Labels: 1.1, updated content

#67 Simplify install instructions with pg-version
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
  getting-started/installation-docker.md
  getting-started/installation-homebrew.md
  getting-started/installation-source-windows.md
  getting-started/installation-windows.md
  getting-started/installation-yum.md
Labels: 1.2

#73 Add license and last_tuned examples in telemetry docs
  using-timescaledb/telemetry.md
Labels: 1.2

#74 Clarify the lack of max_parallel_workers setting in PG9.6
  getting-started/configuring.md
Labels: 0.10

#69 Add documentation for time_bucket_gapfill
  api.md
  using-timescaledb/reading-data.md
Labels: 1.2

#77 Fix statements that partitions must be prefixes of UNIQUE
  using-timescaledb/schema-management.md
  using-timescaledb/writing-data.md
Labels: 0.8

#82 Include enterprise license key in getting started
  api.md
  getting-started/exploring-enterprise.md
Labels: 1.2, new page

#83 Update getting started to explain license key setting
  getting-started/exploring-enterprise.md
Labels: 1.2

#86 Clarify that drop_chunks operates on chunk time constraints
  api.md
Labels: 1.1

#84 Add tip about building OSS-only binaries
  getting-started/exploring-enterprise.md
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
  getting-started/installation-docker.md
  getting-started/installation-homebrew.md
  getting-started/installation-source-windows.md
  getting-started/installation-source.md
  getting-started/installation-windows.md
  getting-started/installation-yum.md
Labels: 1.2

#89 Update CentOS instructions to use packagecloud
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
  getting-started/installation-yum.md
Labels: 1.0

#81 Add section on timescaledb-tune to Configuration
  getting-started/configuring.md
Labels: 1.2

#95 Add tip for installing Apache binaries
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
  getting-started/installation-docker.md
  getting-started/installation-homebrew.md
  getting-started/installation-yum.md
Labels: 1.2

#98 Add timescaledb-tune to install pages
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
  getting-started/installation-homebrew.md
  getting-started/installation-yum.md
Labels: 1.2
