Repository timescale/docs.timescale.com-content, pull requests merged in 2019-11, with the labels that each got.

#242 Update prometheus tutorial after breaking changes
  tutorials/prometheus-adapter.md
Labels: 1.0

#253 [fix]Fix more nits
  api.md
  using-timescaledb/move_chunk.md
Labels: 1.5

#245 Update multinode demo
  tutorials/clustering.md
Labels: clustering, multinode

#255 Update api.md
  api.md
Labels: 1.5

#244 Add contributing instructions
  README.md
Labels: 0.8

#258 [fix]Correct API errors
  api.md
Labels: 1.5

#260 Update AMIs for 1.5.1
  getting-started/installation-ubuntu-ami.md
Labels: 1.5

#261 [fix]Fix minor typos
  api.md
  using-timescaledb/compression.md
  using-timescaledb/reading-data.md
Labels: 1.5

#263 [fix]Add locf reference
  using-timescaledb/reading-data.md
Labels: 0.10

#264 [fix]Replace anchor
  using-timescaledb/reading-data.md
Labels: 1.4
