Repository timescale/docs.timescale.com-content, pull requests merged in 2019-05, with the labels that each got.

#133 Add new fields to telemetry example
  using-timescaledb/telemetry.md
Labels: 1.3

#134 Add docs for drop_chunks with continuous aggs
  api.md
Labels: 1.3

#135 API changes for continuous aggregates
  api.md
Labels: 1.3

#130 Add docs for our CREATE INDEX
  api.md
Labels: 1.3

#131 Add documentation for continuous aggregates
  api.md
  page-index/page-index.js
  using-timescaledb/continuous-aggregates.md
Labels: 1.3

#136 Add docs for pre/post restoring functions & physical backups
  api.md
  using-timescaledb/backup.md
Labels: 1.3

#132 Document telemetry_metadata
  using-timescaledb/telemetry.md
Labels: 1.3

#143 Fix typo in cont aggs tutorial
  tutorials/continuous-aggs-tutorial.md
Labels: 1.3

#141 Describe time_partitioning_func feature
  api.md
Labels: 1.1

#146 Relocated some content
  faq.md
  introduction/timescaledb-vs-nosql.md
Labels: 1.2

#148 Change version defaults for install pages
  page-index/page-index.js
Labels: 1.1
