Repository timescale/docs.timescale.com-content, pull requests merged in 2019-04, with the labels that each got.

#117 Add references to outflux
  getting-started/migrating-data.md
  tutorials.md
Labels: 0.8

#118 Prevent parser from reading text as header
  getting-started/migrating-data.md
Labels: 0.8

#116 Add content for Outlux tutorial
  tutorials/outflux.md
Labels: 0.8

#120 Improve Outflux Tutorial content formatting
  tutorials/outflux.md
Labels: 0.8

#122 Switch API command list function order to alphabetical
  api.md
Labels: 0.8

#126 Change all references to the database to 'TimescaleDB'
  api.md
  faq.md
  getting-started/creating-hypertables.md
  getting-started/installation-docker.md
  getting-started/installation-ubuntu-ami.md
  getting-started/migrating-data.md
  introduction/architecture.md
  introduction/data-model.md
  introduction/timescaledb-vs-postgres.md
  starting-from-scratch.md
  tutorials/replication.md
  using-timescaledb.md
  using-timescaledb/telemetry.md
Labels: 0.8

#124 Update data retention instructions to use policy scheduler
  using-timescaledb/data-retention.md
Labels: 1.2, 1.3

#129 tutorial for continuous aggregates
  page-index/page-index.js
  tutorials.md
  tutorials/continuous-aggs-tutorial.md
Labels: 1.3
