Repository timescale/docs.timescale.com-content, pull requests merged in 2019-10, with the labels that each got.

#225 Updating description of add_data_node
  api.md
Labels: clustering

#226 Update documentation for attach_data_node and detach_data_node
  api.md
Labels: clustering

#228 Install removal
  getting-started/clustering-installation.md
  page-index/page-index.js
Labels: multinode

#233 Update the scaling out section
  getting-started/scaling-out.md
Labels: multinode

#230 Update multinode-related content in the architecture section
  introduction/architecture.md
Labels: multinode

#235 Add distributed_exec to the API docs
  api.md
Labels: clustering, multinode

#238 Update the examples in the multinode tutorial
  tutorials/clustering.md
Labels: clustering, multinode

#237 Add documentation for {block,allow}_new_chunks
  api.md
Labels: clustering

#232 Document password authentication for multinode
  getting-started.md
  getting-started/data-node-authentication.md
  page-index/page-index.js
Labels: clustering

#236 Update the clustering tutorial
  tutorials/clustering.md
Labels: clustering

#231 Update the section on using Hypertables
  using-timescaledb/hypertables.md
Labels: clustering, multinode

#239 Add a Limitations section
  getting-started/scaling-out.md
  page-index/page-index.js
  using-timescaledb/limitations.md
Labels: clustering, multinode

#229 Move subsection separation as tip refers to refresh materialization
  api.md
Labels: 1.3

#246 Update data node authentication section
  getting-started/data-node-authentication.md
Labels: multinode

#249 Update AMI images
  getting-started/installation-ubuntu-ami.md
Labels: 1.5

#251 Update AMI IDs to correct ones for 1.5.0
  getting-started/installation-ubuntu-ami.md
Labels: 1.5
