Repository timescale/docs.timescale.com-content, pull requests merged in 2020-11, with the labels that each got.

#575 Fixing broken links in multi-node auth setup
  getting-started/setup-multi-node-auth.md
Labels: 2.0, add-to-branches

#576 Correct spelling mistakes
  api.md
Labels: 2.0

#578 Fix broken links
  update-timescaledb/update-tsdb-1.md
  update-timescaledb/update-tsdb-2.md
Labels: 2.0, add-to-branches

#547 Add promscale info to telemetry example
  using-timescaledb/telemetry.md
Labels: 1.7, add-to-branches

#580 Fix links in using actions
  using-timescaledb/actions.md
Labels: 2.0, add-to-branches

#579 Add Timescale Forge setup docs to left nav
  getting-started/exploring-forge.md
  getting-started/installation-timescale-forge.md
  page-index/page-index.js
Labels: 1.7, 2.0, add-to-branches

#581 Add Forge installation page
  getting-started/installation-timescale-forge.md
  page-index/page-index.js
Labels: 1.7, 1.x-only, add-to-branches

#582 Update instructions for adding new data nodes
  api.md
  getting-started/setup-multi-node-auth.md
  getting-started/setup-multi-node-basic.md
Labels: 2.0, add-to-branches, multinode

#586 Update release notes with 2.0 RC3
  release-notes.md
Labels: 2.0, add-to-branches

#589 Update docker instructions to RC3
  getting-started/installation-docker.md
  update-timescaledb/update-docker.md
Labels: 2.0, add-to-branches

#585 Update Forge installation page
  getting-started/installation-timescale-forge.md
Labels: 2.0, add-to-branches

#587 Add multi-node-specific settings and other tweaks
  getting-started/setup-multi-node-auth.md
  getting-started/setup-multi-node-basic.md
  using-timescaledb/distributed-hypertables.md
Labels: 2.0, add-to-branches, multinode

#591 Add Release Notes subscription form to pages
  page-index/page-index.js
Labels: 2.0, add-to-branches

#592 Update Changes to link RC3 and clarify refresh
  release-notes/changes-in-timescaledb-2.md
Labels: 2.0, add-to-branches
