Repository timescale/docs.timescale.com-content, pull requests merged in 2020-07, with the labels that each got.

#386 Sunset Prometheus tutorial
  page-index/page-index.js
  tutorials.md
  tutorials/tutorial-setup-timescale-prometheus.md
Labels: 1.7, add-to-branches

#437 Update AMI images for 1.7.2
  getting-started/installation-ubuntu-ami.md
Labels: 1.7

#438 Add release notes for 1.7.1 and 1.7.2
  release-notes.md
Labels: 1.7

#441 Fix grafana URL to .com not .org
  tutorials/tutorial-grafana.md
  tutorials/tutorial-setup-timescale-prometheus.md
  tutorials/tutorial-use-timescale-prometheus-grafana.md
Labels: 1.7

#447 Link mulitnode bootstrap description when related
  api.md
  getting-started/scaling-out.md
  page-index/page-index.js
Labels: 2.0, add-to-branches

#443 Make nav into adjective: Set up -> Setting up
  page-index/page-index.js
Labels: 1.7

#449 Remove nav to enterprise and data tiering
  page-index/page-index.js
  using-timescaledb/compression.md
Labels: 1.7

#450 Improve warning about multinode beta
  getting-started/clustering-installation.md
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
  getting-started/installation-homebrew.md
  getting-started/installation-timescale-cloud.md
  getting-started/installation-ubuntu-ami.md
  getting-started/installation-windows-azure.md
  getting-started/installation-windows.md
  getting-started/installation-yum.md
  getting-started/scaling-out.md
  introduction/architecture.md
  tutorials/clustering.md
Labels: 2.0, add-to-branches

#451 Add PG 12 and fix convention
  tutorials/clustering.md
Labels: 2.0, multinode

#452 Reorganize multi-node instructions
  getting-started/scaling-out.md
  getting-started/setup-multi-node.md
  page-index/page-index.js
  using-timescaledb/distributed-hypertables.md
Labels: 2.0

#423 Update documentation regarding pg_upgrade
  api.md
  using-timescaledb/update-db.md
Labels: 1.7, 2.0, add-to-branches

#456 Fix typo in tutorial link
  tutorials.md
Labels: 1.6, add-to-branches

#457 Fix multi-node docs nits
  getting-started/setup-multi-node.md
  introduction/architecture.md
Labels: 2.0
