Repository timescale/docs.timescale.com-content, pull requests merged in 2020-06, with the labels that each got.

#411 Add a new Node tutorial
  page-index/page-index.js
  tutorials.md
  tutorials/quickstart-node.md
  tutorials/quickstart-ruby.md
Labels: 1.6

#392 Remove cascade option from drop_chunks
  api.md
Labels: 2.0, add-to-branches

#418 Update interface for drop_chunks and friends
  api.md
  introduction/timescaledb-vs-postgres.md
  using-timescaledb/data-retention.md
Labels: 2.0

#416 Added a section to the tutorial on dynamic panels
  tutorials/tutorial-grafana-variables.md
Labels: 1.5

#426 Added Getting Started guide for Timescale Forge
  getting-started/exploring-forge.md
  page-index/page-index.js
Labels: 1.7

#421 Add PG12 supporting compression
  api.md
  using-timescaledb/compression.md
Labels: 1.7, add-to-branches

#422 Support compression on all PG versions
  api.md
  using-timescaledb/compression.md
Labels: 2.0

#432 Remove version of current compression restriction
  api.md
Labels: 1.5, add-to-branches

#410 Add suggestions and limitations around gapfill
  api.md
Labels: 1.7, add-to-branches

#435 Fix nits with Forge getting started
  getting-started/exploring-forge.md
Labels: 1.7
