Repository timescale/docs.timescale.com-content, pull requests merged in 2020-01, with the labels that each got.

#268 Add compression-related informational views
  api.md
Labels: 1.5

#277 Update AMI for 1.6.0
  getting-started/installation-ubuntu-ami.md
Labels: 1.6

#274 Update Telegraf version to 1.13.0
  tutorials/telegraf-output-plugin.md
Labels: 1.0

#283 [WIP] Release Notes & Future Plans
  release-notes.md
Labels: docs

#281 Document set_replication_factor
  api.md
Labels: clustering

#280 Adding new option for detach/delete_data_node
  api.md
Labels: clustering

#266 Add description of data node bootstrapping
  multinode/bootstrapping.md
  page-index/page-index.js
Labels: clustering

#276 new Timescale Labs tutorial
  getting-started/exploring-labs.md
  page-index/page-index.js
Labels: 1.6, docs

#284 Fix table typo
  introduction/data-model.md
Labels: 0.8
