Repository timescale/docs.timescale.com-content, pull requests merged in 2020-03, with the labels that each got.

#307 Document ignore_invalidation_older_than
  api.md
  tutorials/continuous-aggs-tutorial.md
  using-timescaledb/continuous-aggregates.md
Labels: 1.7

#313 Add Timescale Cloud security doc
  getting-started/securing-timescale-cloud.md
  page-index/page-index.js
Labels: 1.5

#316 Add Cryptocurrency and Tableau tutorials
  page-index/page-index.js
  tutorials.md
  tutorials/analyze-cryptocurrency-data.md
  tutorials/visualizing-time-series-data-in-tableau.md
Labels: 1.5

#326 Remove enterprise tag
  api.md
  using-timescaledb/data-retention.md
Labels: 1.7

#290 Add note about deadlock during create_hypertable
  api.md
Labels: 1.6

#336 Document drop-chunk policies
  api.md
Labels: 1.6

#335 Updating documentation for drop_chunks
  api.md
Labels: 1.6

#331 Document certificate authentication
  getting-started/data-node-authentication.md
Labels: multinode

#340 Moving updates for 1.6.1 to master branch
  api.md
Labels: 1.6, add to branches

#338 Fixed capitalization in caggs_stats example
  api.md
Labels: 1.3, add to branches

#339 Expand examples with alter_job_schedule
  api.md
Labels: 1.6, add to branches

#345 Update AMIs for 1.6.1
  getting-started/installation-ubuntu-ami.md
Labels: 1.6

#347 Update release notes for 1.6.1
  release-notes.md
Labels: 1.6

#351 Clarify that update must be first command run in a psql session
  using-timescaledb/update-db.md
Labels: 0.8, add to branches

#314 Info about data retention for continous aggregates
  using-timescaledb/data-retention.md
Labels: 1.7, add to branches
