Repository timescale/docs.timescale.com-content, pull requests merged in 2020-09, with the labels that each got.

#478 Modified time-series forecasting doc with preamble
  tutorials/tutorial-forecasting.md
Labels: 1.5

#480 Add 1.7.3 and 1.7.4 release notes
  release-notes.md
Labels: 1.7, add-to-branches

#481 Update AMIs for 1.7.4
  getting-started/installation-ubuntu-ami.md
Labels: 1.7, add-to-branches

#483 Update apt package versions
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
Labels: 1.7

#497 Update approximate_row_count api
  api.md
Labels: 2.0

#495 Update timescaledb_information views
  api.md
Labels: 2.0

#500 Remove enterprise license
  README.md
  api.md
  getting-started/exploring-enterprise.md
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
  getting-started/installation-docker.md
  getting-started/installation-homebrew.md
  getting-started/installation-source-windows.md
  getting-started/installation-source.md
  getting-started/installation-windows-azure.md
  getting-started/installation-windows.md
  getting-started/installation-yum.md
  page-index/page-index.js
  using-timescaledb/move_chunk.md
  using-timescaledb/telemetry.md
Labels: 2.0

#496 Update continuous aggregate API functions
  api.md
Labels: 2.0

#499 Add size related functions
  api.md
Labels: 2.0

#503 Add timescaledb_information.job_stats
  api.md
Labels: 2.0

#504 Initial run at some updates to the Hello, Timescale!
  tutorials/tutorial-hello-timescale.md
Labels: 1.7

#505 Added a Golang quick start tutorial to docs
  page-index/page-index.js
  tutorials/quickstart-go.md
Labels: 1.6
