Repository timescale/docs.timescale.com-content, pull requests merged in 2020-10, with the labels that each got.

#507 Remove block and allow new chunks API
  api.md
Labels: multinode

#493 Update chapter on using continuous aggregates
  using-timescaledb/continuous-aggregates.md
Labels: 2.0, add-to-branches

#494 Custom Jobs
  api.md
  page-index/page-index.js
  using-timescaledb/actions.md
Labels: 2.0, add-to-branches

#510 Update views related to policies
  api.md
Labels: 2.0

#511 Update parameter names for size functions
  api.md
Labels: 2.0

#519 Update view column names
  api.md
Labels: 2.0

#516 Update parameter names for several functions
  api.md
Labels: 2.0

#522 Add quotes in certificate authentication setup
  getting-started/setup-multi-node.md
Labels: 2.0

#521 Add type and make descriptions consistent
  api.md
Labels: 2.0

#502 Update retention documentation for 2.0
  api.md
  using-timescaledb/continuous-aggregates.md
  using-timescaledb/data-retention.md
Labels: 2.0, add-to-branches

#515 Update compression docs to reflect 2.0 changes
  api.md
  using-timescaledb/compression.md
Labels: 2.0

#528 Fix typo in community function keyword
  api.md
Labels: 2.0

#517 Update introduction to continuous aggregates
  api.md
  using-timescaledb/continuous-aggregates.md
Labels: 2.0, add-to-branches

#529 Add if_attached argument to detach_data_node() api
  api.md
Labels: 2.0, add-to-branches

#526 Fixed the tutorials cover page to include missing tutorials.
  tutorials.md
Labels: 1.6, add-to-branches

#531 Applied the wrong SQL chunk for the displayed example
  tutorials/tutorial-forecasting.md
Labels: 1.5

#508 Add sample datasets size
  tutorials/other-sample-datasets.md
Labels: 1.7, add-to-branches

#532 Updates to api doc
  api.md
Labels: 2.0, add-to-branches

#534 Add quotes to some variables
  getting-started/setup-multi-node-auth.md
Labels: 2.0, add-to-branches

#530 Sunset pg_prometheus and adapter, add references to Promscale
  getting-started/installation-docker.md
  page-index/page-index.js
  tutorials.md
  tutorials/prometheus-adapter.md
  tutorials/tutorial-setting-up-timescale-cloud-endpoint-for-prometheus.md
  tutorials/tutorial-setup-timescale-prometheus.md
  tutorials/tutorial-use-timescale-prometheus-grafana.md
  using-timescaledb/ingesting-data.md
Labels: 1.7, add-to-branches

#538 Add TIP how to install specific version
  getting-started/setup.md
Labels: 1.7

#536 Remove references to continuous_aggregate_stats from api.md
  api.md
  using-timescaledb/continuous-aggregates.md
  using-timescaledb/move_chunk.md
Labels: 2.0, add-to-branches

#509 Clarify single hypertable in continuous aggregate
  api.md
Labels: 1.7, add-to-branches

#535 Remove cascade_to_materializations from drop_chunks
  api.md
Labels: 2.0, add-to-branches

#533 Improve create_distributed_hypertable
  api.md
Labels: 2.0, add-to-branches

#514 Add instructions for backfill to compressed data
  using-timescaledb/compression.md
Labels: 1.7, add-to-branches

#542 Clarify tips about ssl_dir
  getting-started/setup-multi-node-auth.md
  getting-started/setup-multi-node.md
Labels: 2.0

#539 Updated data tiering section
  api.md
  page-index/page-index.js
  using-timescaledb/data-tiering.md
  using-timescaledb/move_chunk.md
Labels: 2.0, add-to-branches

#541 Update add_data_node() API description
  api.md
Labels: 2.0, add-to-branches

#543 Changes for TimescaleDB 2.0.0-rc2 launch
  faq.md
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
  getting-started/installation-docker.md
  getting-started/installation-homebrew.md
  getting-started/installation-timescale-cloud.md
  getting-started/installation-ubuntu-ami.md
  getting-started/installation-windows.md
  getting-started/installation-yum.md
  getting-started/release-notes/changes-in-timescaledb-2.md
  getting-started/setup-multi-node.md
  introduction/architecture.md
  page-index/page-index.js
  release-notes.md
  tutorials/clustering.md
  update-timescaledb.md
  update-timescaledb/update-docker.md
  update-timescaledb/update-tsdb-1.md
  update-timescaledb/update-tsdb-2.md
  update-timescaledb/upgrade-pg.md
  using-timescaledb.md
  using-timescaledb/distributed-hypertables.md
  using-timescaledb/troubleshooting.md
Labels: 2.0

#544 Update release notes with RC1 and RC2 info
  release-notes.md
Labels: 2.0

#545 Cleanup based on PR feedback.
  getting-started/release-notes/changes-in-timescaledb-2.md
Labels: 2.0, add-to-branches

#549 Fixed back-tick formatting and URLs
  getting-started/release-notes/changes-in-timescaledb-2.md
Labels: 2.0, add-to-branches

#550 Fix typo
  api.md
Labels: 1.7, 2.0, add-to-branches

#552 Removed beta warning and broken link for distributed hypertables
  using-timescaledb/distributed-hypertables.md
Labels: 2.0

#551 Fix minor grammar in create_distributed_hypertable
  api.md
Labels: 2.0, add-to-branches

#556 Clarify that compression policy not supported in multinode
  using-timescaledb/limitations.md
Labels: 2.0, add-to-branches

#557 Fix minor errors in ALTER VIEW
  api.md
Labels: 1.7, 2.0

#555 Update and expand the section on distributed hypertables
  page-index/page-index.js
  using-timescaledb/distributed-hypertables.md
  using-timescaledb/hypertables.md
Labels: 2.0, add-to-branches

#559 Update limitations section for multi-node
  using-timescaledb/backup.md
  using-timescaledb/limitations.md
Labels: 2.0

#565 Moving around GUC changes and cagg function references
  api.md
  getting-started/configuring.md
  page-index/page-index.js
  release-notes/changes-in-timescaledb-2.md
Labels: 2.0, add-to-branches

#566 Clarify retention policy on integer-based time
  api.md
Labels: 2.0, add-to-branches

#567 Add anchor links to distributed hypertable subsubsections
  using-timescaledb/distributed-hypertables.md
Labels: 2.0, add-to-branches

#568 Add limitation related to UDFs on distributed hypertables
  using-timescaledb/limitations.md
Labels: 2.0, add-to-branches

#564 Clarify space partitioning due to multi-node
  api.md
Labels: 2.0, add-to-branches, multinode

#570 Remove errant git 'HEAD' line
  api.md
Labels: 1.7, 1.x-only

#562 Add multinode role-adding instructions
  getting-started/setup-multi-node-auth.md
  getting-started/setup-multi-node-basic.md
  page-index/page-index.js
Labels: 2.0, add-to-branches

#571 Clarify limitation of start and finish in gapfill
  api.md
Labels: 1.7, 2.0, add-to-branches
