Repository timescale/docs.timescale.com-content, pull requests merged in 2020-04, with the labels that each got.

#333 Document materialized_only option
  api.md
Labels: 1.7, add to branches

#354 Update references to 'Hello NYC' tutorial
  tutorials/tutorial-forecasting.md
Labels: 0.8

#355 Deprecate PG9.6 and PG10 for 1.7.0
  getting-started/configuring.md
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
  getting-started/installation-homebrew.md
  getting-started/installation-source-windows.md
  getting-started/installation-source.md
  getting-started/installation-windows.md
  getting-started/installation-yum.md
Labels: 1.7

#325 Add section on integer-based continuous aggregates
  page-index/page-index.js
  tutorials/continuous-aggs-tutorial.md
  using-timescaledb/continuous-aggregates.md
Labels: 1.7, add to branches

#352 Add tutorial: How to monitor a Django application with Prometheus.
  page-index/page-index.js
  tutorials.md
  tutorials/tutorial-howto-monitor-django-prometheus.md
Labels: 1.5, add to branches

#362 Describe how to drop chunks from aggregate
  using-timescaledb/data-retention.md
Labels: 1.6, add to branches

#359 Merge securing cloud access into Timescale Cloud section
  getting-started/exploring-cloud.md
  getting-started/securing-timescale-cloud.md
  page-index/page-index.js
Labels: 1.6, add to branches

#367 Update AMI values for 1.7.0
  getting-started/installation-ubuntu-ami.md
Labels: 1.7

#364 Add Quick Starts for Python and Ruby
  page-index/page-index.js
  tutorials.md
  tutorials/quickstart-python.md
  tutorials/quickstart-ruby.md
Labels: 1.6, add to branches

#368 Document materialized_only in timescaledb_information.continuous_aggregates
  api.md
Labels: 1.7, add to branches

#365 Add instructions for rebasing and squashing commits properly.
  development/contribute-to-docs.md
Labels: 1.5, add to branches

#356 Use constant notation for constants
  api.md
  introduction/timescaledb-vs-postgres.md
  tutorials/prometheus-adapter.md
  tutorials/telegraf-output-plugin.md
  tutorials/tutorial-forecasting.md
  using-timescaledb/compression.md
  using-timescaledb/data-retention.md
  using-timescaledb/move_chunk.md
  using-timescaledb/reading-data.md
  using-timescaledb/writing-data.md
Labels: 1.7, add to branches

#350 Update using continuous aggregate chapter
  using-timescaledb/continuous-aggregates.md
Labels: 1.7, add to branches

#371 [fix]Update mislabelled code blocks
  tutorials/quickstart-python.md
  tutorials/tutorial-grafana.md
Labels: 1.5

#366 Update release-notes.md
  release-notes.md
Labels: 1.7, add to branches

#353 Add tutorials: Missing data on Grafana, Generate a basic sample IoT dataset
  page-index/page-index.js
  tutorials.md
  tutorials/tutorial-howto-simulate-iot-sensor-data.md
  tutorials/tutorial-howto-visualize-missing-data-grafana.md
Labels: 1.3, add to branches

#376 Add real-time aggregates to continuous aggs
  page-index/page-index.js
  using-timescaledb/continuous-aggregates.md
Labels: 1.7

#374 Add PostgreSQL 12 as installation option
  page-index/page-index.js
Labels: 1.7, add to branches

#377 Remove sidebar link to Timescale Labs
  page-index/page-index.js
Labels: 1.7, add to branches

#378 Fix broken link for creating superuser
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
  getting-started/installation-yum.md
Labels: 1.7, add to branches

#383 [fix]Add redirect for new tutorial filename
  page-index/page-index.js
Labels: 1.5, bug
