Repository timescale/docs.timescale.com-content, pull requests merged in 2020-05, with the labels that each got.

#390 Refactor Grafana tutorial into smaller tutorials
  getting-started/installation-grafana.md
  tutorials/tutorial-grafana-dashboards.md
  tutorials/tutorial-grafana-geospatial.md
  tutorials/tutorial-grafana-variables.md
  tutorials/tutorial-grafana.md
Labels: 1.6

#391 Fixed Grafana tutorial links
  tutorials.md
  tutorials/tutorial-grafana.md
Labels: 1.6

#395 Update AMI values for 1.7.1
  getting-started/installation-ubuntu-ami.md
Labels: 1.7

#396 Add Grafana alerts tutorial
  page-index/page-index.js
  tutorials/tutorial-grafana-alerts.md
  tutorials/tutorial-grafana.md
Labels: 1.5, add-to-branches

#399 fixed typo on "Microsoft"
  getting-started/exploring-cloud.md
Labels: 1.7

#405 Fix tutorial-grafana-dashboards link
  tutorials/tutorial-grafana.md
Labels: 1.6, add-to-branches

#401 Remove third-party Azure install method
  page-index/page-index.js
Labels: 1.5, 1.6, 1.7

#408 Minor changes
  tutorials/quickstart-python.md
Labels: 1.6, add-to-branches
