Repository timescale/docs.timescale.com-content, pull requests merged in 2020-08, with the labels that each got.

#465 Fix description add_reorder_policy
  api.md
Labels: 1.2, add-to-branches

#466 Label automation as community feature
  api.md
Labels: 1.7, add-to-branches

#468 [fix] Improper img tags
  tutorials/tutorial-forecasting.md
Labels: 0.8, add-to-branches

#469 Document compress_chunk/decompress_chunk optional args
  api.md
Labels: 1.5

#467 [fix] Update release notes urls
  release-notes.md
Labels: 1.7, add-to-branches

#474 Update AMI for 1.7.3
  getting-started/installation-ubuntu-ami.md
Labels: 1.7, add-to-branches
