Repository timescale/docs.timescale.com-content, pull requests merged in 2020-12, with the labels that each got.

#610 Remove codeowners from 1.7 branch
  CODEOWNERS
Labels: 1.7, 1.x-only, add-to-branches

#608 Update release notes for new rc version
  release-notes.md
Labels: 1.7, 1.x-only, add-to-branches

#609 Update release notes for rc4
  release-notes.md
Labels: 2.0, add-to-branches

#607 Improve rpm package installation docs
  getting-started/installation-yum.md
Labels: 2.0, add-to-branches

#611 Adding instructions for creating a multi-node cluster in Timescale Forge
  getting-started/forge-multi-node.md
  getting-started/setup-multi-node-basic.md
  page-index/page-index.js
Labels: 2.0, add-to-branches

#612 Small nits to multi-node on Forge doc
  getting-started/forge-multi-node.md
Labels: 2.0, add-to-branches

#614 Make 1.7.4 branch changes to yum installation
  getting-started/installation-yum.md
Labels: 1.7, 1.x-only, add-to-branches

#606 Add admin privileges as a prereq for windows install
  getting-started/installation-windows.md
Labels: 1.7, add-to-branches

#604 Add note about removal of Enterprise tier
  getting-started/exploring-enterprise.md
Labels: 1.7, add-to-branches

#601 Add maintenance job to heal data nodes
  getting-started/setup-multi-node-auth.md
Labels: 2.0, add-to-branches

#600 Set timescaledb.max_background_workers with timescaledb-tune
  getting-started/configuring.md
Labels: 1.7, add-to-branches, blocked

#613 Fix nits for Forge multi-node page
  getting-started/forge-multi-node.md
  getting-started/setup-multi-node-basic.md
Labels: 2.0, add-to-branches

#615 Add hypertable to cagg information view
  api.md
  release-notes/changes-in-timescaledb-2.md
Labels: 2.0, add-to-branches

#617 Add redirect for old clustering branch page
  page-index/page-index.js
Labels: 1.7, add-to-branches

#616 Timescale Forge changes to reflect new settings feature, resize and some distributed hypertable language
  getting-started/exploring-forge.md
  getting-started/forge-configuration.md
  getting-started/forge-resize.md
  page-index/page-index.js
  using-timescaledb/distributed-hypertables.md
Labels: 2.0, add-to-branches

#618 Fix is_compressed column description for chunks view
  api.md
Labels: 2.0, 2.x-only, add-to-branches

#619 Internal hostname for Forge multi-node and updated anchor tags
  getting-started/exploring-forge.md
  getting-started/forge-configuration.md
  getting-started/forge-multi-node.md
Labels: 2.0, add-to-branches

#621 Update AMI for 2.0.0
  getting-started/installation-ubuntu-ami.md
Labels: 2.0

#628 Update AMIs to have correct package
  getting-started/installation-ubuntu-ami.md
Labels: 2.0, 2.x-only

#631 Clarify limitation of background scheduling
  using-timescaledb/limitations.md
Labels: 2.0, add-to-branches

#632 Require relation in show_chunks
  api.md
Labels: 2.0, add-to-branches
