Repository timescale/docs.timescale.com-content, pull requests merged in 2021-02, with the labels that each got.

#650 Update AMIs for 2.0.1
  getting-started/installation-ubuntu-ami.md
Labels: 2.0, 2.x-only, add-to-branches

#643 Add MacPorts installation method
  getting-started/installation-macports.md
  page-index/page-index.js
Labels: 1.7, 1.x-only, add-to-branches

#651 Remove beta warnings on multi-node
  getting-started/setup-multi-node.md
  introduction/architecture.md
  tutorials/clustering.md
Labels: 2.0, add-to-branches

#652 Added latest minor releases from CHANGELOG
  release-notes.md
Labels: 2.0, add-to-branches

#654 Promscale docs
  page-index/page-index.js
  tutorials/getting-started-with-promscale.md
  tutorials/promscale-benefits.md
  tutorials/promscale-how-it-works.md
  tutorials/promscale-install.md
  tutorials/promscale-run-queries.md
Labels: 2.0, add-to-branches

#655 Typo in Continuous Aggregates quick-start
  using-timescaledb/continuous-aggregates.md
Labels: 2.0, add-to-branches

#657 Update continuous-aggregates.md
  using-timescaledb/continuous-aggregates.md
Labels: 1.7, add-to-branches

#658 Add PG13 as supported version for 2.1
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
  getting-started/installation-homebrew.md
  getting-started/installation-source-windows.md
  getting-started/installation-source.md
  getting-started/installation-windows.md
  getting-started/installation-yum.md
  page-index/page-index.js
  tutorials/clustering.md
  update-timescaledb.md
  update-timescaledb/update-tsdb-2.md
Labels: 2.1, add-to-branches

#663 Schema changes that are permitted with compression
  api.md
  using-timescaledb/compression.md
Labels: 2.1

#665 Update AMIs for 2.0.2
  getting-started/installation-ubuntu-ami.md
Labels: 2.0, 2.x-only

#668 Fix title formatting for compression
  using-timescaledb/compression.md
Labels: 2.1, add-to-branches

#669 Minor change for new 4TB size update in Forge
  getting-started/forge-resize.md
Labels: 2.x-only, add-to-branches

#667 Release notes for 2.1
  release-notes.md
Labels: 2.1, add-to-branches
