Repository timescale/docs.timescale.com-content, pull requests merged in 2021-03, with the labels that each got.

#661 Add example with getting hypertable size across all hypertables
  api.md
Labels: 2.0, add-to-branches

#659 Add example for dropping chunks across all hypertables
  api.md
Labels: 2.0, add-to-branches

#676 Fix typo on troubleshooting page
  using-timescaledb/troubleshooting.md
Labels: 1.7, add-to-branches

#677 Fix update docker instructions to use GA
  update-timescaledb/update-docker.md
Labels: 2.0, add-to-branches

#678 Update to 4TB storage
  getting-started/exploring-forge.md
Labels: 2.0, add-to-branches

#666 Clarify cagg refresh window requirements
  api.md
Labels: 2.0, 2.1, add-to-branches

#680 Remove experimental warning for tablespaces
  api.md
Labels: 1.7, 2.0, add-to-branches

#673 Add create_distributed_restore_point() description
  api.md
Labels: 2.2, add-to-branches

#687 Update documentation for hypertable size functions
  api.md
Labels: 2.2, add-to-branches

#689 Updating service creation flow to include smaller instances with 0.25…
  getting-started/exploring-forge.md
Labels: 1.7, 2.0, add-to-branches

#693 Fix names of informational views in scaling out tutorial
  tutorials/clustering.md
Labels: 2.0

#690 fix: small errors
  tutorials/tutorial-hello-timescale.md
Labels: 1.7, add-to-branches

#695 Add release notes for 2.1.1
  release-notes.md
Labels: 2.1, add-to-branches

#691 Add FAQ question for Timescale hosted in by other clouds
  faq.md
Labels: 1.5, add-to-branches
