Repository timescale/docs.timescale.com-content, pull requests merged in 2021-04, with the labels that each got.

#671 Rearrange organization of current/future releases
  release-notes.md
Labels: 2.1, add-to-branches

#699 Update AMI for 2.1.1
  getting-started/installation-ubuntu-ami.md
Labels: 2.1, 2.x-only, add-to-branches

#703 Add release notes for 2.2.0
  release-notes.md
Labels: 2.2, add-to-branches

#704 Update AMI images for 2.2.0
  getting-started/installation-ubuntu-ami.md
Labels: 2.2, add-to-branches
