Repository timescale/docs.timescale.com-content, pull requests merged in 2021-01, with the labels that each got.

#630 Remove installation multinode warnings
  getting-started/installation-homebrew.md
  getting-started/installation-ubuntu-ami.md
Labels: 2.0, add-to-branches

#633 Clarify versions which require database restart
  using-timescaledb/update-db.md
Labels: 1.7, 2.0, add-to-branches

#625 CMake 3.11 is now required
  getting-started/installation-source-windows.md
  getting-started/installation-source.md
Labels: 2.0, add-to-branches

#634 Update copyright year to 2021
  NOTICE
Labels: add-to-branches

#599 Modified the Getting Started page with more content
  getting-started.md
Labels: 2.0, add-to-branches, blocked

#636 docs: fix data-retention link
  using-timescaledb/continuous-aggregates.md
Labels: 1.6, add-to-branches

#640 Add clarification on "statement_timeout" for self-hosted
  getting-started/multi-node-self-managed.md
Labels: 2.0, 2.x-only, add-to-branches

#639 Added future plans and reworded for GA
  release-notes.md
Labels: 2.0, add-to-branches

#642 Re-add MacOS to installation methods
  page-index/page-index.js
Labels: 2.0, add-to-branches

#638 Clarify supported ALTER MATERIALIZE VIEW options
  api.md
Labels: 2.0, add-to-branches

#646 Update continuous-aggregates.md
  using-timescaledb/continuous-aggregates.md
Labels: 2.0, 2.x-only, add-to-branches

#635 Remove reference to TimescaleDB Release Candidates and upgrades given…
  getting-started/forge-multi-node.md
  getting-started/installation-apt-debian.md
  getting-started/installation-apt-ubuntu.md
  getting-started/installation-yum.md
Labels: 2.0, add-to-branches

#644 Clarify limitations when creating hypertables
  api.md
Labels: 2.0, add-to-branches, enhancement

#649 Fix broken link to hello-timescale page
  tutorials/quickstart-go.md
Labels: 1.7, 2.0, add-to-branches
