Repository timescale/docs.timescale.com-content, pull requests merged in 2021-05, with the labels that each got.

#711 Update AMIs for 2.2.1
  getting-started/installation-ubuntu-ami.md
Labels: 2.2, add-to-branches

#713 Fix/fix typo
  tutorials/replication.md
Labels: 1.6, add-to-branches

#714 Update AMIs for 2.3.0
  getting-started/installation-ubuntu-ami.md
Labels: 2.3
